---
title: Project 2
---


# CSC106: Project 2

* due Monday 5/4/26 by 11:59 pm
* you may use [late token(s)](https://forms.gle/WXW44b2AM6kQCdX16) for this assignment

In this project, you’ll implement several variants of a text-based Rock-Paper-Scissors game in which a human player plays against the computer. If you’re not familiar with the game, check out the Wikipedia article about it:
(<http://en.wikipedia.org/wiki/Rock-paper-scissors>)



* Reminder: Programming projects should be done individually. You should not look at anyone else’s code, show your code to anyone else, write code for anyone else, or let someone else write code for you. Consider anyone else to include any form of AI. Please see the syllabus or course website for what to do when you need help with your work.
* Projects are graded on program correctness and code composition, including proper commenting
* This project is 10% of your final grade

* starter code:
    + [rps_1.py](https://georgiadoing.github.io/CSC106-S26/Data/starter_code/rps_1.py)
    + [rps_2.py](https://georgiadoing.github.io/CSC106-S26/Data/starter_code/rps_2.py)
    + [game_history.py](https://georgiadoing.github.io/CSC106-S26/Data/starter_code/game_history.py)
    + [rps_anti_human.py](https://georgiadoing.github.io/CSC106-S26/Data/starter_code/rps_anti_human.py)
    + [rps_human_like.py](https://georgiadoing.github.io/CSC106-S26/Data/starter_code/rps_human_like.py)


::: {.content-visible when-format="html"}
<iframe src="../Data/CSC106_Proj2_rock_paper_scissors.pdf" width="100%" height="800" style="border:none;"></iframe>
:::

```{=latex}

\includepdf[pages=-]{../Data/CSC106_Proj2_rock_paper_scissors.pdf}

```