---
title: CSC 106 Can Computers Think?, Programming Project 1
date: Sept, 28, 2026
eval: true
format: 
    pdf:
        number-sections: false
        shift-heading-level-by: 2
        geometry:
            - top=1in
            - right=.8in
            - bottom=1in
            - left=.8in
        mainfont: "Avenir"
        sansfont: "Avenir"
        code-line-numbers: truei
        include-in-header: 
            - ../preamble2.tex
---

NAME:  


# Project 1: Drawings with Turtle  (Rubric)


|                            | Meeting/exceeding expectations (full points)        | Arriving at expectations  (partial points)          | Not meeting Expectations    (Low or no points)     |   |
|----------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------|---|
| Programs (2 pts)       | All programs are correct  (1 pt)   | All programs run, some programs are correct   (.5 pt)      | Program(s) don't run or fewer than half of programs are correct          |   |
|                            |        |                   |                      |   |
|                            | Programs are logical and organized  (.5 pt)     |  Programs are logical or organized (.3 pt)  | Programs are neither logical nor organized    |   |
|                            |        |                   |                      |   |
|                            | Clear headers and in-line comments  (.5 pt)  | Either clear headers or good in-line comments   (.3 pt)    | All comments are lacking clarity     |   |
|                            |        |                   |                      |   |
| Demo  (3 pts)|  Answers all questions thoroughly, clearly understands their program(s)   (1 pt)         |        Answers most questions thoroughly but required prompting    (.75 pt)    |  Can not explain all or part of the program(s)  |   |
|                            |        |                   |                      |   |
|                            | Responds to follow-up questions with accurate and clear answers  (1 pt)     |   Responds to follow-up questions but cannot carry out a conversation   (.5 pt)    |  Cannot  demonstrate understanding     
|                            |        |                   |                      |   |
|                | Student identified what their biggest challenge was and how they overcame it.  (1 pt) | Student identified areas for improvement but lacked specificity. (.5 pt)  | Reflection lacked consideration.|   |

# Files


1.  [	][	]	`square.py`
2.	[	][	]	`rectangle.py`
3.	[	][	]	`circle.py`
4.	 [	][	]	`triangle.py`
5.	 [	][	]	`turtle_shapes.py`
6.	 [	][	]	`my_picture.py`
7.	 [	][	]	`five_random_numbers.py`
8.	 [	][	]	`computer_art.py`
9.   [	][	]	`my_picture.png`
10.  [	][	]	`computer_art.png`

# Answers/notes

1. How did you fill in the bodies of the shape functions? *what python/turtle functions did you use? what variables?*

2. What additional functions did you define? *what are their names? parameters? what use? how many times?*

3. What variables did you define? *names? values? purposes? re-use? re-assign?*

4. What will your drawing show when it is run? *what is the main subject? other details should I look out for?*


………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………



5. What was the most challenging part of the project? *multiple iterations? what would you do differently next time?*


………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………





